language: ruby
cache: bundler
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
